import { LandingContent } from './types';

export const defaultLandingContent: LandingContent = {
  brandName: "AETHER // AI",
  brandTagline: "Next-Gen AI Core",
  navLinks: [
    { id: "nav-solutions", label: "Solutions", href: "#features" },
    { id: "nav-results", label: "Results", href: "#metrics" },
    { id: "nav-testimonials", label: "Testimonials", href: "#testimonials" },
    { id: "nav-docs", label: "Docs", href: "#cta" },
  ],
  hero: {
    badgePillText: "New v2.4",
    badgePillLinkText: "[ANNOUNCEMENT / CORE FEATURE PILL] →",
    headline: "[MAIN VALUE PROPOSITION",
    headlineHighlight: "FOR NEXT-GEN AI]",
    description: "[SHORT DESCRIPTION — A concise 2-3 sentence overview highlighting how your AI technology solves the problem statement, streamlines workflows, and delivers unprecedented precision.]",
    primaryCtaText: "[PRIMARY CTA]",
    secondaryCtaText: "Explore Docs",
  },
  featuresHeading: {
    sectionTag: "ARCHITECTURAL CAPABILITIES",
    title: "[VALUE PROPOSITION IN DETAIL]",
    description: "Modular, high-throughput components designed to integrate seamlessly into modern developer and enterprise ecosystems.",
  },
  features: [
    {
      id: "feature-1",
      number: "01",
      tag: "REAL-TIME REASONING",
      title: "[VALUE / FEATURE 01 TITLE]",
      description: "[Detailed explanation of feature 01. Describe the algorithmic advantage, data processing capability, and user benefits.]",
      iconName: "Cpu",
      metricHighlight: "< 42ms Inference Latency",
      codeSnippet: "// Core Execution Pipeline\nconst stream = await ai.synthesize({\n  mode: 'autonomous',\n  precision: 'ultra-high'\n});",
    },
    {
      id: "feature-2",
      number: "02",
      tag: "AUTONOMOUS ORCHESTRATION",
      title: "[VALUE / FEATURE 02 TITLE]",
      description: "[Detailed explanation of feature 02. Describe how multi-agent collaboration or automated decision workflows accelerate outcomes.]",
      iconName: "Network",
      metricHighlight: "99.98% Verification Score",
      codeSnippet: "// Multi-Agent Consensus\nawait cluster.dispatchAgents([\n  'analyzer',\n  'synthesizer',\n  'verifier'\n]);",
    },
    {
      id: "feature-3",
      number: "03",
      tag: "ZERO-CONFIG SCALING",
      title: "[VALUE / FEATURE 03 TITLE]",
      description: "[Detailed explanation of feature 03. Emphasize developer velocity, enterprise security compliance, and seamless cross-platform deployment.]",
      iconName: "Layers",
      metricHighlight: "10x Throughput Boost",
      codeSnippet: "// Distributed Edge Topology\nexport const config = {\n  regions: ['global'],\n  failover: 'instantaneous'\n};",
    },
  ],
  metricsHeading: {
    sectionTag: "VERIFIABLE IMPACT",
    title: "[PROOF & RESULTS OVERVIEW]",
    description: "Quantified performance gains and operational multipliers benchmarked against legacy architectures.",
  },
  metrics: [
    {
      id: "metric-1",
      label: "[METRIC 01 — LATENCY / SPEED]",
      value: "14.2",
      suffix: "x",
      trend: "+340% velocity",
      description: "[RESULT 01 — Acceleration in processing speed, response time, or throughput compared to baseline models.]",
    },
    {
      id: "metric-2",
      label: "[METRIC 02 — ACCURACY / ACCORD]",
      value: "99.94",
      suffix: "%",
      trend: "Zero hallucinations",
      description: "[RESULT 02 — High confidence benchmark across complex contextual reasoning, verification, and classification.]",
    },
    {
      id: "metric-3",
      label: "[METRIC 03 — PRODUCTIVITY SAVINGS]",
      value: "82",
      suffix: "%",
      trend: "Hours saved weekly",
      description: "[RESULT 03 — Measurable reduction in manual engineering overhead, repetitive tasks, and cognitive load.]",
    },
    {
      id: "metric-4",
      label: "[METRIC 04 — COST EFFICIENCY]",
      value: "6.8",
      prefix: "$",
      suffix: "M+",
      trend: "Value created",
      description: "[IMPACT 04 — Total resource optimization and cost savings achieved across production deployments.]",
    },
  ],
  testimonialsHeading: {
    sectionTag: "COMMUNITY & ENTERPRISE VOICES",
    title: "Don't just take our word for it",
    description: "Discover the speed, clarity, and intelligence of our AI solution. Built for hyper-productivity across engineering, design, and research workflows.",
  },
  pressLogos: [
    { id: "p1", name: "The Washington Post" },
    { id: "p2", name: "GIZMODO" },
    { id: "p3", name: "Forbes" },
    { id: "p4", name: "WIRED" },
    { id: "p5", name: "TechCrunch" },
    { id: "p6", name: "The Verge" },
  ],
  testimonialsLane1: [
    {
      id: "test-1",
      name: "Alex Rivera",
      role: "Lead Architect @ Quantum Labs",
      handle: "@alexrivera_ai",
      platform: "x",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
      content: "With this AI core, we gained full visibility and automated control over our multi-stage pipeline. What used to take weeks of manual code generation now completes in real-time.",
    },
    {
      id: "test-2",
      name: "Dr. Elena Rostova",
      role: "VP of Engineering @ Synthetix",
      handle: "@erostova_tech",
      platform: "x",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
      content: "The seamless contextual reasoning transformed our developer productivity. It accurately understands complex schema constraints without needing repetitive prompting.",
    },
    {
      id: "test-3",
      name: "Marcus Vance",
      role: "Founder @ Autonomous Stack",
      handle: "@marcus_vance",
      platform: "x",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
      content: "What stands out is not just the extreme inference speed, but the absolute reliability. Our engineering velocity tripled within the first 48 hours of onboarding.",
    },
    {
      id: "test-4",
      name: "Sarah Chen",
      role: "Head of AI Product @ HyperScale",
      handle: "@schen_builds",
      platform: "x",
      avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
      content: "The intelligent automation layer handles 85% of our triage and data mapping flawlessly. The team can now focus purely on high-leverage product innovations.",
    },
  ],
  testimonialsLane2: [
    {
      id: "test-5",
      name: "Devon Thorne",
      role: "Chief Technology Officer @ NeuralEdge",
      handle: "@devon_thorne",
      platform: "x",
      avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80",
      content: "This platform has been a total game-changer for our productivity metrics. Unified our data sources, accelerated reporting by 10x, and eliminated debugging friction.",
    },
    {
      id: "test-6",
      name: "Aaliyah Patel",
      role: "Staff Researcher @ Cognitive Systems",
      handle: "@aaliyah_patel",
      platform: "x",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
      content: "The deep contextual recall and multi-modal synthesis allow our research team to synthesize literature and benchmark models 4x faster than ever before.",
    },
    {
      id: "test-7",
      name: "Kaito Tanaka",
      role: "Director of Software @ ApexRobotics",
      handle: "@kaito_tanaka",
      platform: "x",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
      content: "Deploying AI agents that actually reason and self-correct on edge clusters seemed years away. This architecture made it painless and rock solid.",
    },
    {
      id: "test-8",
      name: "Jessica Miller",
      role: "Design & UX Lead @ FlowState AI",
      handle: "@jmiller_ux",
      platform: "x",
      avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
      content: "The micro-interactions, responsive agent feedback, and instant code synthesis saved our team over 25 hours per sprint. It feels like magic every day.",
    },
  ],
  finalCta: {
    badgeText: "DEPLOY IN SECONDS",
    headline: "[FINAL VALUE PROPOSITION — READY TO ACCELERATE?]",
    description: "[SHORT CTA TEXT — Join pioneering developers and high-velocity teams building the next era of intelligent AI-driven applications today.]",
    primaryCtaText: "[CTA BUTTON — GET STARTED NOW]",
    secondaryCtaText: "Schedule Technical Demo",
    footnote: "No credit card required • Instant API key provisioning • Open SDKs",
  },
  footer: {
    copyright: "© 2026 AI Core Systems, Inc. All rights reserved.",
    links: [
      { label: "Privacy Policy", href: "#" },
      { label: "Terms of Service", href: "#" },
      { label: "Security & SOC2", href: "#" },
      { label: "Status", href: "#" },
      { label: "GitHub", href: "https://github.com" },
    ],
  },
};

export const samplePresets: Record<string, { label: string; description: string; data: Partial<LandingContent> }> = {
  universal: {
    label: "Universal Placeholder (Hackathon Default)",
    description: "Standard clean placeholders ready for any problem statement",
    data: defaultLandingContent,
  },
  agentic: {
    label: "Autonomous AI Agents & Reasoning",
    description: "Multi-agent autonomous orchestration and sub-second reasoning",
    data: {
      brandName: "NEURAL//NEXUS",
      hero: {
        badgePillText: "Agentic OS",
        badgePillLinkText: "Explore Autonomous Agent Mesh v3.0 →",
        headline: "Deploy Autonomous Multi-Agent Swarms",
        headlineHighlight: "with Mathematical Precision",
        description: "Orchestrate specialized AI agents that collaborate, inspect tool outputs, self-correct logic errors, and execute complex workflows without manual supervision.",
        primaryCtaText: "Initialize Swarm ↗",
        secondaryCtaText: "Read Whitepaper",
      },
      featuresHeading: {
        sectionTag: "CORE CAPABILITIES",
        title: "Built for Autonomous Execution",
        description: "Enterprise-grade infrastructure designed for agentic loops, sub-second tool execution, and continuous memory recall.",
      },
    },
  },
  copilot: {
    label: "AI Developer Platform & Copilot",
    description: "Autonomous code synthesis, continuous security verification, and DX tools",
    data: {
      brandName: "DEV//GENIX",
      hero: {
        badgePillText: "DevCore AI",
        badgePillLinkText: "Instant Codebase Synthesis v2.4 →",
        headline: "The Autonomous Pair Programmer",
        headlineHighlight: "for High-Velocity Teams",
        description: "Transform natural language specs into production-ready full-stack architectures, automated test suites, and verified security patches in seconds.",
        primaryCtaText: "Start Building Free ↗",
        secondaryCtaText: "View Documentation",
      },
      featuresHeading: {
        sectionTag: "DEVELOPER EXPERIENCE",
        title: "From Idea to Production at Warp Speed",
        description: "Instant semantic graph analysis, automated pull request generation, and zero-latency code completions.",
      },
    },
  },
  medtech: {
    label: "HealthTech & Bio-Inference AI",
    description: "Multi-modal bio-imaging and clinical validation pipelines",
    data: {
      brandName: "BIO//SYNAPSE",
      hero: {
        badgePillText: "Clinical AI",
        badgePillLinkText: "Multi-Modal Diagnostic Core v4.1 →",
        headline: "Accelerating Clinical Discoveries",
        headlineHighlight: "with Explainable AI",
        description: "Harness multi-modal bio-imaging synthesis, genomic pattern recognition, and real-time clinical notes validation to empower researchers and physicians worldwide.",
        primaryCtaText: "Request Research Access ↗",
        secondaryCtaText: "Clinical Validation",
      },
      featuresHeading: {
        sectionTag: "CLINICAL RESEARCH",
        title: "Precision Medicine at Planetary Scale",
        description: "HIPAA-compliant, cryptographically verified inference engine trained on verified medical telemetry and genomic sequences.",
      },
    },
  },
};
