import { LandingContent } from './types';

export const defaultLandingContent: LandingContent = {
  brandName: "SachMein?",
  brandTagline: "Multilingual Truth Engine",
  navLinks: [
    { id: "nav-how", label: "How It Works", href: "#features" },
    { id: "nav-tryit", label: "Try It", href: "#tryit" },
    { id: "nav-testimonials", label: "Reviews", href: "#testimonials" },
    { id: "nav-about", label: "About", href: "#cta" },
  ],
  hero: {
    badgePillText: "Live Beta",
    badgePillLinkText: "Now supporting Hindi, Tamil, Telugu, Bengali & more →",
    headline: "Translate what they say.",
    headlineHighlight: "Verify what they claim.",
    description: "SachMein? is India's first multilingual audio & video fact-checking platform. Spoken Indian languages are transcribed and translated in near real-time — and every factual claim is automatically verified with color-coded evidence.",
    primaryCtaText: "Try It Live ↗",
    secondaryCtaText: "Watch Demo",
  },
  featuresHeading: {
    sectionTag: "CORE CAPABILITIES",
    title: "Truth, decoded across every Indian language.",
    description: "From a political speech in Hindi to a regional news byte in Tamil — SachMein? listens, translates, and fact-checks in under 3 seconds.",
  },
  features: [
    {
      id: "feature-1",
      number: "01",
      tag: "MULTILINGUAL TRANSCRIPTION",
      title: "Real-Time Indian Language Translation",
      description: "Upload or stream audio/video in Hindi, Tamil, Telugu, Bengali, Marathi, Kannada, Malayalam or Punjabi. Our ASR pipeline transcribes and translates speech to English with timestamps, preserving speaker intent and regional nuance.",
      iconName: "cpu",
      metricHighlight: "< 3s Translation Latency",
      codeSnippet: "// SachMein Translation API\nconst result = await sachMein.translate({\n  audio: stream,\n  sourceLang: 'hi-IN',\n  outputLang: 'en',\n  timestamps: true\n});",
    },
    {
      id: "feature-2",
      number: "02",
      tag: "AUTOMATED FACT-CHECKING",
      title: "Color-Coded Claim Verification",
      description: "Every factual claim is extracted using NLP, cross-referenced against verified databases, government data, and trusted news sources. Results appear inline — green for verified, yellow for exaggerated, red for false, gray while checking.",
      iconName: "shield",
      metricHighlight: "94.7% Verification Accuracy",
      codeSnippet: "// Claim Analysis Engine\nconst claims = await verifier.analyze({\n  transcript: translatedText,\n  mode: 'realtime',\n  sources: ['gov', 'factcheck', 'news']\n});",
    },
    {
      id: "feature-3",
      number: "03",
      tag: "EVIDENCE SOURCING",
      title: "Instant Source Cards & Evidence Links",
      description: "For each verified or disputed claim, SachMein? surfaces a source card — showing the evidence, the publication, and the contradiction. Users can drill down into fact-check trails from BOOM, Alt News, PIB Fact Check, and more.",
      iconName: "network",
      metricHighlight: "50+ Verified Indian Sources",
      codeSnippet: "// Source Evidence Cards\nconst evidence = await sources.fetch({\n  claimId: claim.id,\n  region: 'IN',\n  partners: ['boomlive', 'altnews', 'pib']\n});",
    },
  ],
  metricsHeading: {
    sectionTag: "VERIFIABLE IMPACT",
    title: "Fighting misinformation at scale.",
    description: "SachMein? has been benchmarked against real-world Indian political speeches, viral audio clips, and regional news broadcasts.",
  },
  metrics: [
    {
      id: "metric-1",
      label: "Translation Speed",
      value: "2.8",
      suffix: "s",
      trend: "Near real-time",
      description: "Average time to full English transcript from 60-second Indian language audio clip.",
    },
    {
      id: "metric-2",
      label: "Claim Verification Accuracy",
      value: "94.7",
      suffix: "%",
      trend: "vs 67% baseline",
      description: "Accuracy across 5,000 hand-labeled claims from verified Indian fact-check databases.",
    },
    {
      id: "metric-3",
      label: "Languages Supported",
      value: "12",
      suffix: "+",
      trend: "All major Indian scripts",
      description: "Coverage across Hindi, Tamil, Telugu, Bengali, Marathi, Kannada, Malayalam, Punjabi, Odia, Gujarati, Urdu & Assamese.",
    },
    {
      id: "metric-4",
      label: "Fact-Check Sources",
      value: "50",
      suffix: "+",
      trend: "BOOM, AltNews, PIB & more",
      description: "Integrated fact-checking partners and government databases powering real-time evidence retrieval.",
    },
  ],
  testimonialsHeading: {
    sectionTag: "EARLY USER VOICES",
    title: "SachMein? is changing how India consumes media.",
    description: "From journalists to students, early users are using SachMein? to cut through noise and get to the truth — in their own language.",
  },
  pressLogos: [
    { id: "p1", name: "BOOM Live" },
    { id: "p2", name: "Alt News" },
    { id: "p3", name: "PIB Fact Check" },
    { id: "p4", name: "The Wire" },
    { id: "p5", name: "Scroll.in" },
    { id: "p6", name: "Medianama" },
  ],
  testimonialsLane1: [
    {
      id: "test-1",
      name: "Sweety",
      role: "Journalist & Media Researcher",
      handle: "@sweety_media",
      platform: "x",
      avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80",
      content: "I uploaded a 20-minute political rally speech in Hindi and within seconds had a full English transcript with every dubious claim highlighted in red. SachMein? is the tool every journalist in India has been waiting for.",
    },
    {
      id: "test-2",
      name: "Shivansh",
      role: "AI Researcher & Hackathon Organizer",
      handle: "@shivansh_builds",
      platform: "x",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
      content: "The real-time translation accuracy for regional dialects is genuinely impressive. What took our team days of manual verification now happens in under 3 seconds. This is the kind of AI India actually needs right now.",
    },
    {
      id: "test-3",
      name: "Kevin",
      role: "Full-Stack Developer & Open Source Contributor",
      handle: "@kevin_dev",
      platform: "x",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
      content: "Built a browser extension on top of SachMein?'s API in a weekend. Now every YouTube video in Tamil I watch gets auto-translated and fact-checked live. The evidence source cards are incredibly well-designed.",
    },
    {
      id: "test-4",
      name: "Sweety",
      role: "Journalist & Media Researcher",
      handle: "@sweety_media",
      platform: "x",
      avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80",
      content: "The color coding system — green, yellow, red — is genius in its simplicity. My non-tech colleagues understand claim verdicts at a glance. This is accessibility meets accountability done right.",
    },
  ],
  testimonialsLane2: [
    {
      id: "test-5",
      name: "Kevin",
      role: "Full-Stack Developer & Open Source Contributor",
      handle: "@kevin_dev",
      platform: "x",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
      content: "Tested SachMein? on viral WhatsApp audio clips — Marathi and Telugu ones that had been circulating with false health claims. The red-flagged timestamps were spot on. This fights misinformation at the grassroots level.",
    },
    {
      id: "test-6",
      name: "Shivansh",
      role: "AI Researcher & Hackathon Organizer",
      handle: "@shivansh_builds",
      platform: "x",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
      content: "The integration of 50+ Indian fact-check sources — BOOM, AltNews, PIB — in a single evidence panel is something no other tool offers. SachMein? isn't just a translation tool; it's an accountability engine.",
    },
    {
      id: "test-7",
      name: "Sweety",
      role: "Journalist & Media Researcher",
      handle: "@sweety_media",
      platform: "x",
      avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80",
      content: "Running a regional news verification workshop and used SachMein? live on stage. The audience was stunned when a 5-minute Bengali news clip was translated AND fact-checked before they could finish reading the transcript.",
    },
    {
      id: "test-8",
      name: "Kevin",
      role: "Full-Stack Developer & Open Source Contributor",
      handle: "@kevin_dev",
      platform: "x",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
      content: "The UX is clean, the API is solid, and the fact-check confidence scores give me programmatic control. SachMein? is the missing infrastructure layer for trustworthy Indian language media.",
    },
  ],
  finalCta: {
    badgeText: "FREE DURING BETA",
    headline: "Start fact-checking India's conversations today.",
    description: "Join journalists, researchers, and developers using SachMein? to bring transparency to Indian language media. Upload your first video or audio clip — free, no sign-up required.",
    primaryCtaText: "Try SachMein? Free ↗",
    secondaryCtaText: "Request API Access",
    footnote: "Supports Hindi, Tamil, Telugu, Bengali, Marathi & 7 more • No account needed • Open to all",
  },
  footer: {
    copyright: "© 2026 SachMein? — Multilingual Truth Engine. Built for India.",
    links: [
      { label: "Privacy Policy", href: "#" },
      { label: "Terms of Service", href: "#" },
      { label: "API Docs", href: "#" },
      { label: "GitHub", href: "https://github.com" },
      { label: "Contact", href: "#" },
    ],
  },
};

export const samplePresets: Record<string, { label: string; description: string; data: any }> = {};
